### ISSUE TITLE
Windows dependencies resolution

### ISSUE THREAD

**Issue by aahmed-se** [njlr/apache-pulsar-demo#1]
This occurs in my win 10 env with buckaroo 2.2.0 
buck version 2019.01.10.01

Don't see in osx env.

```
The target 'buckaroo.github.buckaroo-pm.icu4c//:icu4c' tried to reference 'source\samples\cal\uprint.h'.
This is not allowed because 'source\samples\cal\uprint.h' can only be referenced from 'source\samples\cal\BUCK'
which is its closest parent 'BUCK' file.

You should find or create a rule in 'source\samples\cal\BUCK' that references
'source\samples\cal\uprint.h' and use that in 'buckaroo.github.buckaroo-pm.icu4c//:icu4c'
instead of directly referencing 'source\samples\cal\uprint.h'.
More info at:
https://buckbuild.com/concept/build_rule.html

This issue might also be caused by a bug in buckd's caching.
Please check whether using `buck kill` resolves it.

This error happened while trying to get dependency 'buckaroo.github.buckaroo-pm.icu4c//:icu4c' of target 'buckaroo.github.buckaroo-pm.boost-regex//:regex'
```

**Comment by njlr** [comment]
Try doing a `buckaroo upgrade`. I think this issue was fixed recently.

**Comment by njlr** [comment]
BTW, the port of icu4c does not currently work on Windows since it requires MinGW. We will have to find a work-around.

**Comment by aahmed-se** [comment]
is it something in the port

this says it should compile fine
https://wiki.qt.io/Compiling-ICU-with-MSVC

I ran buckaroo upgrade but still the same issue

```
The target 'buckaroo.github.buckaroo-pm.icu4c//:icu4c' tried to reference 'source\samples\cal\uprint.h'.
This is not allowed because 'source\samples\cal\uprint.h' can only be referenced from 'source\samples\cal\BUCK'
which is its closest parent 'BUCK' file.

You should find or create a rule in 'source\samples\cal\BUCK' that references
'source\samples\cal\uprint.h' and use that in 'buckaroo.github.buckaroo-pm.icu4c//:icu4c'
instead of directly referencing 'source\samples\cal\uprint.h'.
More info at:
https://buckbuild.com/concept/build_rule.html

This issue might also be caused by a bug in buckd's caching.
Please check whether using `buck kill` resolves it.

This error happened while trying to get dependency 'buckaroo.github.buckaroo-pm.icu4c//:icu4c' of target 'buckaroo.github.buckaroo-pm.boost-regex//:regex'
```

**Comment by njlr** [comment]
That link is for Cygwin builds

**Comment by aahmed-se** [comment]
will have to look into this further
